'use strict';
const $=s=>document.querySelector(s);let catalog={Libraries:[],Items:[]},library='',type='',limit=40,featured=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok){if(r.status===401&&path!='/auth/login'){location.reload()}throw Error(data.error||'Anfrage fehlgeschlagen')}return data}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),4500)}
function show(page){$('#collection').classList.toggle('hidden',page!=='collection');$('#settings').classList.toggle('hidden',page!=='settings');$('#collection-nav').classList.toggle('active',page==='collection');$('#settings-nav').classList.toggle('active',page==='settings');$('#page-title').textContent=page==='collection'?'Sammlung':'Verbindungen'}
function img(item,kind='Primary'){return '/api/images/'+encodeURIComponent(item.Id)+'/'+kind}
function render(){const all=catalog.Items||[];let items=all.filter(i=>(!library||i.LibraryId===library)&&(!type||i.Type===type)&&i.Name.toLocaleLowerCase().includes($('#search').value.toLocaleLowerCase()));items.sort((a,b)=>$('#sort').value==='year'?(b.ProductionYear||0)-(a.ProductionYear||0):$('#sort').value==='rating'?(b.CommunityRating||0)-(a.CommunityRating||0):a.Name.localeCompare(b.Name));$('#item-count').textContent=all.length;$('#updated').textContent=catalog.Updated&&!catalog.Updated.startsWith('0001')?'Aktualisiert '+new Date(catalog.Updated).toLocaleString('de-CH'):'Noch nicht synchronisiert';$('#grid').innerHTML=items.slice(0,limit).map(i=>`<article class="movie"><button class="poster" data-id="${esc(i.Id)}" aria-label="${esc(i.Name)} – Details">${i.ImageTags?.Primary?`<img loading="lazy" src="${img(i)}" alt="${esc(i.Name)}">`:`<span class="poster-fallback">${esc(i.Name)}</span>`}${i.CommunityRating?`<span class="rating">★ ${i.CommunityRating.toFixed(1)}</span>`:''}<span class="download-indicator">${i.IsFolder?'↗':'↓'}</span></button><h3>${esc(i.Name)}</h3><p>${i.ProductionYear||'–'} &nbsp;·&nbsp; ${esc(i.Genres?.[0]||i.Type)}</p></article>`).join('');$('#empty').classList.toggle('hidden',items.length>0);$('#empty h3').textContent=all.length?'Keine passenden Titel.':'Platz für deine Lieblingsfilme.';$('#empty p').textContent=all.length?'Passe deine Suche oder die Filter an.':'Verbinde Emby unter „Verbindungen“ und synchronisiere deine Sammlung.';$('#more').classList.toggle('hidden',items.length<=limit);document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>detail(b.dataset.id));document.querySelectorAll('#grid img').forEach(i=>i.onerror=()=>{const s=document.createElement('span');s.className='poster-fallback';s.textContent=i.alt;i.replaceWith(s)})}
function renderCatalog(){catalog.Items??=[];catalog.Libraries??=[];$('#libraries').innerHTML=catalog.Libraries.map(l=>`<button class="nav" data-lib="${esc(l.Id)}">▤ <span>${esc(l.Name)}</span></button>`).join('');document.querySelectorAll('[data-lib]').forEach(b=>b.onclick=()=>{library=library===b.dataset.lib?'':b.dataset.lib;document.querySelectorAll('[data-lib]').forEach(x=>x.classList.toggle('active',x.dataset.lib===library));show('collection');limit=40;render()});featured=catalog.Items.find(i=>i.BackdropImageTags?.length&&!i.IsFolder)||catalog.Items.find(i=>!i.IsFolder);if(featured){$('#hero h2').textContent=featured.Name;$('#hero-copy').textContent=featured.Overview||'Entdecke diesen Titel in deiner Sammlung.';$('#hero-action').textContent='Titel entdecken ↗';if(featured.BackdropImageTags?.length)$('#hero').style.backgroundImage=`url("${img(featured,'Backdrop')}")`;}render()}
function detail(id){const i=catalog.Items.find(i=>i.Id===id);if(!i)return;$('#detail-content').innerHTML=`<div class="detail-grid"><div>${i.ImageTags?.Primary?`<img src="${img(i)}" alt="${esc(i.Name)}">`:''}</div><div><small>${esc(i.Type)} / ${i.ProductionYear||'–'}</small><h2>${esc(i.Name)}</h2><p>${esc((i.Genres||[]).join(' · '))}${i.RunTimeTicks?' · '+Math.round(i.RunTimeTicks/600000000)+' Min.':''}</p><p>${esc(i.Overview||'Keine Beschreibung in Emby hinterlegt.')}</p>${i.CommunityRating?`<p>★ ${i.CommunityRating.toFixed(1)} / 10</p>`:''}${i.IsFolder?'<p>Downloads sind bei den einzelnen Filmen und Episoden verfügbar.</p>':`<a class="button primary" href="/api/download/${encodeURIComponent(i.Id)}">Datei herunterladen ↓</a>`}</div></div>`;$('#detail').showModal()}
async function settings(){const s=await api('/api/settings');const f=$('#settings-form');for(const key of ['EmbyURL','SourceMode','SourcePrefix'])f.elements[key].value=s[key]||'';f.elements.APIKey.value='';$('#key-help').textContent=s.HasAPIKey?'Schlüssel gespeichert. Leer lassen, um ihn beizubehalten.':'In Emby unter Erweitert → API-Schlüssel erstellen.';$('#connection-status').textContent=s.EmbyURL?'Konfiguriert':'Noch nicht verbunden';$('#oidc-status').textContent=s.OIDC?'OIDC aktiv':'OIDC nicht eingerichtet'}
async function start(){const s=await api('/api/session');$('#oidc').classList.toggle('hidden',!s.oidc);if(!s.user)return;$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');$('#user').textContent=s.user;await settings();catalog=await api('/api/catalog');renderCatalog()}
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/auth/login',Object.fromEntries(new FormData(e.target)));e.target.reset();await start()}catch(e){$('#login-error').textContent=e.message}finally{b.disabled=false}};
$('#logout').onclick=async()=>{try{await api('/auth/logout',{});location.reload()}catch(e){toast(e.message)}};
$('#collection-nav').onclick=()=>{library='';show('collection');render()};$('#settings-nav').onclick=()=>show('settings');$('#hero-action').onclick=()=>featured?detail(featured.Id):show('settings');$('#close-detail').onclick=()=>$('#detail').close();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};
$('#settings-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('/api/settings',Object.fromEntries(new FormData(e.target)));await settings();$('#settings-result').textContent='Gespeichert. Jetzt die Sammlung synchronisieren.';toast('Verbindung gespeichert')}catch(e){$('#settings-result').textContent=e.message}finally{b.disabled=false}};
$('#sync').onclick=async()=>{const b=$('#sync');b.disabled=true;b.textContent='↻ Wird synchronisiert …';try{catalog=await api('/api/sync',{});renderCatalog();$('#connection-status').textContent='Verbunden';toast('Sammlung synchronisiert')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='↻ Synchronisieren'}};
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;limit=40;document.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=()=>{limit=40;render()};$('#sort').onchange=render;$('#more').onclick=()=>{limit+=40;render()};start().catch(e=>toast(e.message));
